name: Build and Deploy Node.js App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Get username
        run: echo $USER

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t mouazmalik123/nodejsimages:latest .

      - name: Publish image to Docker Hub
        run: docker push mouazmalik123/nodejsimages:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Create SSH directory and set up keys
        run: |
          set -x
          mkdir -p ~/.ssh || exit 1
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/private_key.pem || exit 1
          chmod 600 ~/.ssh/private_key.pem || exit 1
          ssh-keyscan -H $EC2_HOST >> ~/.ssh/known_hosts || exit 1
        shell: /usr/bin/bash -e {0}
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          EC2_HOST: ${{ secrets.AWS_EC2_HOST }}

      - name: Test SSH Connection
        run: |
          ssh -v -o StrictHostKeyChecking=no -i ~/.ssh/private_key.pem ${{ secrets.SSH_USER }}@${{ secrets.AWS_EC2_HOST }} "echo 'SSH connection successful'"
        
      - name: Deploy to AWS EC2
        run: |
          ssh -v -o StrictHostKeyChecking=no -i ~/.ssh/private_key.pem ${{ secrets.SSH_USER }}@${{ secrets.AWS_EC2_HOST }} "docker pull mouazmalik123/nodejsimages:latest"
          if [ $(ssh -i ~/.ssh/private_key.pem ${{ secrets.SSH_USER }}@${{ secrets.AWS_EC2_HOST }} docker ps -q -f name=nodejs-app-container) ]; then
            ssh -i ~/.ssh/private_key.pem ${{ secrets.SSH_USER }}@${{ secrets.AWS_EC2_HOST }} "docker rm -f nodejs-app-container"
          fi
          ssh -i ~/.ssh/private_key.pem ${{ secrets.SSH_USER }}@${{ secrets.AWS_EC2_HOST }} "docker run -d -p 5000:5000 --name nodejs-app-container mouazmalik123/nodejsimages:latest"
