name: Build and Deploy Node.js App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build Docker image
        run: docker build -t nodejsimages .
      
      - name: Publish image to Docker Hub
        run: docker push nodejsimages:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Pull image from Docker Hub
        run: docker pull nodejsimages:latest
      
      - name: Delete old container
        run: |
          if [ $(docker ps -q -f name=nodejs-app-container) ]; then
            docker rm -f nodejs-app-container
          fi
      
      - name: Run Docker container
        run: docker run -d -p 5000:5000 --name nodejs-app-container nodejsimages:latest
