name: Build and Deploy Node.js App1

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Get username
        run: |
          echo $USER

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t mouazmalik123/nodejsimages:latest .

      - name: Publish image to Docker Hub
        run: docker push mouazmalik123/nodejsimages:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Deploy to AWS EC2
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.AWS_EC2_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            docker pull mouazmalik123/nodejsimages:latest
            if [ $(docker ps -q -f name=nodejs-app-container) ]; then
              docker rm -f nodejs-app-container
            fi
            docker run -d -p 5000:5000 --name nodejs-app-container mouazmalik123/nodejsimages:latest
